# Generated by Django 5.0.2 on 2024-02-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('On-going', 'ongoing'), ('Done', 'Done')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
